### ISSUE TITLE
Run spieldose in production

### ISSUE THREAD

**Issue by popouille** [aportela/spieldose#6]
Hello,

Have a way to run spieldose in production mode with domain name? ot it will be implemented?
Great work

Thank you

**Comment by aportela** [comment]
what do you mean ?

current setting (AppSettings.php) for "production" on twigParams toggles debug assets (small scripts without no debug)

The rest of things should work the same, both in a development environment and in a production environment. It does not matter if you are using a domain with a name or an IP address to access.

Or maybe you mean to use it on a "real" web server (apache, nginx ...) instead of with the embedded php server ?

**Comment by popouille** [comment]
I meant use it on an url as http://www.mydomain.com and without port. This is possible? as the server need to be started with ip and port.

**Comment by aportela** [comment]
If you start the php embebed web server at default http port (80) and point the dns entry to the public ip of this server it should work, I mean:

Start the php embebed server on a machine that can be accessed from the internet with:

``
php -S 0.0.0.0:80 cli-server.php
``
If the machine is not connected directly to the internet (dmz or similar) you will probably need to redirect port 80 to the ip of this machine.

You must also need to modify the dns entry so that www.mydomain.com points to the public ip of your machine

I have yet to prepare a small installation and configuration guide with an apache / nginx server as soon as I have a "stable" version but there are some things that I want to correct before

**Comment by popouille** [comment]
Thank you,

waiting for it :)

**Comment by popouille** [comment]
i can't listen on port 80

Failed to listen on myserverip:80 (reason: Address already in use)

port 80 is already listen by nginx that why i think

**Comment by aportela** [comment]
I have a similar environment in my server

Change php embed server localport to 81

``
php -S 0.0.0.0:81 cli-server.php
``

Set a proxy in nginx:

``
        location /spieldose {
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_pass   http://127.0.0.1:81/;
        }

``

If the (public) machine of nginx is not the same as the machine of php embed web server you need to change 127.0.0.1

Now if your dns name (www.mydomain.com) is pointed to your nginx machine you can type

http://www.mydomain.com/spieldose/

**Comment by popouille** [comment]
it works good with my ip server set instead of 127.0.0.1.

But the ideal is to bind the domain and access spieldose directly with http://www.mydomain.com not http://www.mydomain.com/spieldose/ ^^

**Comment by popouille** [comment]
or maybe keep this way to be able to use a cms on http://www.mydomain.com with spieldose on http://www.mydomain.com/spieldose/

**Comment by aportela** [comment]
Did you try the example of README.md ?

 https://github.com/aportela/spieldose/blob/master/README.md

**Comment by popouille** [comment]
yes i got it working on my plesk installation for the main domain, i put this in vhost config:
   location / {
        try_files $uri /index.php$is_args$args;
proxy_redirect off;
proxy_http_version 1.1;
proxy_pass http://serverip:81/;
    }
